name: Set Up Project

runs:
  using: 'composite'
  steps:
    - name: 'Install PNPM'
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: 10.23.0 # Optional: Specify the desired pnpm version
        # run_install: true # Optional: Automatically run `pnpm install` after setup

    - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
      uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4

    - name: 'Setup Node'
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: 'Cache dependencies'
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install
