name: Set Up Project

runs:
  using: 'composite'
  steps:
    - name: 'Install PNPM'
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: 10.18.1 # Optional: Specify the desired pnpm version
        # run_install: true # Optional: Automatically run `pnpm install` after setup

    - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
      uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4

    - name: 'Setup Node'
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: 'Cache dependencies'
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install
