name: Set Up Project

runs:
  using: 'composite'
  steps:
    - name: 'Install PNPM'
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        version: 10.23.0 # Optional: Specify the desired pnpm version
        # run_install: true # Optional: Automatically run `pnpm install` after setup

    - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
      uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4

    - name: 'Setup Node'
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: 'Cache dependencies'
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install
